apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
repicas: ${(.values.replicacount)}
  selector:
    matchLabels:
      app: ${(.values.name)}
  template:
    metadata:
      labels:
        app: ${(.values.name)}
    spec:
      containers:
      - name: ${(.values.name)}
        image: <Image>
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: <Port>
